### ISSUE TITLE
Cannot create SqlConnection in notebook.

### ISSUE THREAD

**Issue by jden123** [dotnet/try#685] opened 2019-12-09 08:32 UTC
#### Describe the bug
I cannot create SqlConnection in notebook.

When I use the latest version I've got `System.BadImageFormatException`

![image](https://user-images.githubusercontent.com/6513070/70419578-26106980-1a7f-11ea-9b40-1c8b3de9d2de.png)

if I use older version(ex: 4.3) I have `System.NotSupportedException`

![image](https://user-images.githubusercontent.com/6513070/70419767-9919e000-1a7f-11ea-88ff-2fb6cbfba527.png)
 

#### Did this error occur while using `dotnet try` or online?
- [ ] `dotnet-try`
- [x] .NET Jupyter Notebook 
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [x] Other:

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by KevinRansom** [comment] 2019-12-12 23:26
This is a dupe of #636  --- I will manage the resolution with Issue 636.

**Closed** 2019-12-12 23:26 UTC
Labels: .NET Kernel, bug
