### ISSUE TITLE
Part of the code in the code box is not visible

### ISSUE THREAD

**Issue by Gadget-Geek** [dotnet/try#57] opened 2018-02-25 04:39 UTC
When I try to type code into the box I see part of the IntelliSense window, but the rest of it (and the code I am typing) is hidden from view so I cannot see what is being entered and what would be executed if I click run.

![image](https://user-images.githubusercontent.com/15017794/36638174-80745ede-19bb-11e8-818d-4b7ebfd620ac.png)

The webpage is open in Microsoft Edge on Windows 10 Education, version 1709 (Fall Creators Update).

**Comment by Gadget-Geek** [comment] 2018-02-25 04:42
To be specific, the first nine lines are not visible, and I cannot scroll upwards to see them. Everything from the 10th line onwards appears, as seen below:

![image](https://user-images.githubusercontent.com/15017794/36638204-5b70d422-19bc-11e8-9307-a8c945b1a860.png)

**Comment by jonsequitur** [comment] 2018-03-02 17:38
This appears to be caused by the same issue as #25.

**Comment by colombod** [comment] 2018-03-02 23:17
The issue is not fixed

**Comment by colombod** [comment] 2018-03-04 02:03
We released a fix for this Friday @therealpiotr we can close this one

**Comment by TheRealPiotrP** [comment] 2018-03-06 17:57
Thanks for fixing this @colombod!

**Closed by TheRealPiotrP** 2018-03-06 17:57 UTC
