### ISSUE TITLE
Allow to reference a local assembly on Jupyter Notebook Server

### ISSUE THREAD

**Issue by elemount** [dotnet/try#698] opened 2019-12-16 07:02 UTC
**Is your feature request related to a problem? Please describe.**
I want to use the jupyter notebook as a interactive tools, but I have a private version dll need to load. Currently it only support nuget public version dll.

**Describe the solution you'd like**
Support #r "dll path on jupyter notebook server"

**Comment by jonsequitur** [comment] 2019-12-18 00:45
This is supported today assuming the volume where the dll is located is reachable from your Jupyter kernel. It works the same way as in C# Interactive: https://github.com/dotnet/roslyn/wiki/Interactive-Window#r

**Comment by elemount** [comment] 2019-12-18 02:54
@jonsequitur , that is what I want to do, just run the #r as the interactive window. But in fact it **fails**.
When I run command such as 
```
#r "C:\Crc32.NET.dll"
```

or 
```
#r "C:\\Crc32.NET.dll"
```

It will throw 

> Invalid: Command: #r C:\Crc32.NET.dll

But when I run those command on dotnet-script. it can works well.

**Comment by jonsequitur** [comment] 2019-12-19 02:40
Ah. This is a duplicate of #609, which has been fixed.

**Closed** 2020-01-15 03:46 UTC
Labels: .NET Kernel
