### ISSUE TITLE
.NET Editor interactive (online) does not accept edits after the first >run command was issued

### ISSUE THREAD

**Issue by boulderdasher** [dotnet/try#73] opened 2018-04-16 23:53 UTC
The online editor is non-functional after the first >run button/command was issued. Page with issue is: https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/numbers-in-csharp#step-1

**Comment by javierlf** [comment] 2018-04-18 01:01
Mismo problema
Same problem

**Comment by javierlf** [comment] 2018-04-18 01:01
En todas las páginas
No page is working

**Comment by Zyphruss** [comment] 2018-06-17 08:31
It's working fine in Microsoft Edge but only runs once and then makes the input area read-only in Firefox, for me.

**Comment by jonsequitur** [comment] 2018-07-16 20:22
This is a duplicate of #17.

**Closed** 2018-08-21 17:26 UTC
Labels: duplicate
