### ISSUE TITLE
Horizontal scrollbar is nonfunctional

### ISSUE THREAD

**Issue by musicsac** [dotnet/try#25] opened 2017-12-15 01:35 UTC
As I create a lengthy line, I can see my text as I write off the page (with the window scrolling to the right as it should), but the start of the line cannot be viewed by moving the horizontal scrollbar as expected. Arrow keying my cursor to the left is a workaround.
Microsoft Edge 41.16299.15.0
Zoom at 150%

**Comment by jonsequitur** [comment] 2017-12-15 20:57
Additional info: It looks like there's both an outer scrollbar and an inner scrollbar (see screen shot). The inner scrollbar is the editor's scrollbar and does work if you scroll it vertically into view, and the outer scrollbar is an IFRAME scrollbar which we should not be seeing.

![image](https://user-images.githubusercontent.com/547415/34060138-391c7294-e197-11e7-87bb-e8d2dc655e66.png)

**Comment by jonsequitur** [comment] 2017-12-18 20:23
@jdanyow

**Comment by jdanyow** [comment] 2017-12-18 20:24
ack

**Comment by TyOverby** [comment] 2018-01-10 00:31
@jdanyow: Any update on this?

**Comment by jdanyow** [comment] 2018-01-10 14:58
We have someone looking at this. Holidays, other priorities, etc.

https://mseng.visualstudio.com/CSI/_workitems/edit/1147585

**Comment by TyOverby** [comment] 2018-01-10 15:51
@jdanyow: ok, great!  I'll close this one and keep an eye on your issue.  If you need any functionality from us, please don't hesitate to get in touch!

**Comment by jdanyow** [comment] 2018-01-11 01:17
Will do, thanks!

**Comment by wibjorn** [comment] 2018-01-12 18:27
@TyOverby 

Believe this issue to be external to Docs.

TL;DR: Set `overflow: hidden` on the html element inside the iframe.

After some research, I could only reproduce the problem in Edge, but not only on high zoom scenarios. The iframe generated begins on page load correctly with no scrollbars, but when typing something, for example "a" the autosuggest (div.monaco-scrollable-element>div.monaco-list-rows) is given a height greater than the height of the editor box, which is likely causing the scrollbars to appear.

That said, this can all be mitigated by setting a style of `overflow: hidden` on the html element inside the iframe. Let me know if there's anything else I can do to help!

**Comment by TyOverby** [comment] 2018-01-12 18:35
@wibjorn: what happens when you add `overflow: hidden` to the element containing the iframe?

**Comment by wibjorn** [comment] 2018-01-12 21:32
@TyOverby At least when I did it in the Edge dev tools, the extra scrollbars never appear on Edge, even when you let the autosuggest div propagate.

**Comment by wibjorn** [comment] 2018-01-12 21:34
@TyOverby Excuse me, I misunderstood your question. If you set `overflow: hidden` on the element containing the iframe, it has no effect.

**Comment by TyOverby** [comment] 2018-01-12 22:32
If I understand this bug correctly, it seems like there are two elements with scrollbars when the bug is present: 

* One element that docs.microsoft.com controls
* One element that try.dot.net controls

Is that accurate?

**Comment by wibjorn** [comment] 2018-01-12 23:27
From what we saw, the scrollbars are inside the iframe, or resulting from the styles of the iframe. Try placing the overflow hidden on the html element in the iframe, this should fix the problem entirely.

**Comment by colombod** [comment] 2018-03-04 02:05
@TheRealPiotrP this is fixed with the release of the fix for #57 , we should close this

**Comment by TheRealPiotrP** [comment] 2018-03-06 17:57
Thanks for fixing this @colombod!

**Closed by TheRealPiotrP** 2018-03-06 17:57 UTC
