### ISSUE TITLE
typing in interactive window did not work in FF

### ISSUE THREAD

**Issue by majormoise** [dotnet/try#40] opened 2018-01-12 19:39 UTC
Typine in the interactive window did not work in firefox, but did in IE

**Comment by LadyNaggaga** [comment] 2018-02-14 18:16
Was this on docs.microsoft.com or try.net. Also what version of Firefox did you use?

**Comment by TheRealPiotrP** [comment] 2018-02-16 21:55
I believe this is a dupe of #17.

**Closed** 2018-08-21 17:26 UTC
Labels: duplicate
